- name: Installing Mysql Libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography #Installing cryptography module, this is also required and will be used by PyMySQL library
  - PyMySQL #Installing Ansible modules to establish connection with Mysql

- name: Installing Mysql
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Connecting to Mysql Server #Checking DB connectivity. It will fail if Connection was not established.
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ DBPass }}"
    login_host: "{{ ansible_facts['default_ipv4']['address'] }}"
  register: Output
  ignore_errors: true

- name: Configuring Mysql DB 
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ DBPass }}"
  when: Output.failed is true
